#!/usr/bin/env bash
# make-fixtures.sh: build the adversarial metadata fixture corpus for MetadataScrubber.
#
# Every picture is synthetic (gradients, shapes and seeded noise). Every name,
# serial number and ID is invented. GPS positions are public landmarks.
#
# Each metadata location carries a unique planted string, either a canary of the
# form CANARY-<FIXTURE>-<PLACE>-<4 hex> or a plausible marker value such as a
# date. The registry of every planted string, with the tier the spec expects,
# is written to out/canaries.tsv and documented in CANARIES.md.
#
# Needs: exiftool, ImageMagick 7 (magick, with HEIC and WebP), python3 and GNU
# coreutils and findutils (sha1sum, stat -c, find -printf).
# Uses ffmpeg for the motion photo video when present; otherwise a hand-built
# MP4 with the same planted strings. Set FIXTURES_NO_FFMPEG=1 to force that.
#
# Reproducible: no clocks, all noise seeded, single-threaded ImageMagick. The
# same tool versions give byte-identical output (see out/SHA256SUMS).
#
# Usage: tests/fixtures/make-fixtures.sh
# Output: tests/fixtures/out/ (git-ignored), plus out/canaries.tsv,
#         out/exiftool-visibility.tsv, out/exiftool/<fixture>.txt,
#         out/canaries-tables.md and out/SHA256SUMS.

set -euo pipefail
export LC_ALL=C TZ=UTC MAGICK_THREAD_LIMIT=1 OMP_NUM_THREADS=1

HERE=$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)
OUT="$HERE/out"
W="$OUT/.work"
KIT="$HERE/fixturekit.py"
REG="$OUT/canaries.tsv"

for tool in exiftool magick python3; do
  command -v "$tool" >/dev/null || { echo "make-fixtures: $tool is required" >&2; exit 1; }
done
# The list is read whole first: grep -q stops reading early, and with pipefail the
# magick that gets cut off would fail the check.
FORMATS=$(magick -list format)
for fmt in HEIC WEBP; do
  grep -qE "^ *$fmt\*? " <<<"$FORMATS" || { echo "make-fixtures: magick lacks $fmt support" >&2; exit 1; }
done
USE_FFMPEG=0
if [ -z "${FIXTURES_NO_FFMPEG:-}" ] && command -v ffmpeg >/dev/null; then USE_FFMPEG=1; fi

# Start clean, but keep the .gitignore that stops generated binaries being committed.
mkdir -p "$OUT"
find "$OUT" -mindepth 1 -maxdepth 1 ! -name .gitignore -exec rm -rf {} +
printf '%s\n' '# Everything in this folder is generated by ../make-fixtures.sh. Do not commit it.' '*' '!.gitignore' > "$OUT/.gitignore"
mkdir -p "$W"

kit() { python3 "$KIT" "$@"; }

# Registry. canary NAME FILE LOCATION GROUP TIER BASIS [STORED_AS]
#   prints CANARY-NAME-xxxx, where xxxx is the start of the SHA-1 of NAME.
# marker VALUE FILE LOCATION GROUP TIER BASIS [STORED_AS]
#   registers a plausible value (a date, a coordinate string) and prints it.
# BASIS is "spec" when the spec names the item and its tier, "inferred" when
# the spec is silent and the tier follows the closest rule in it.
# STORED_AS is raw (verbatim bytes), zlib (inside a compressed PNG chunk),
# hex (inside a PNG raw profile) or utf16 (UTF-16 text, as Ducky stores it).
# A marker may add EXIFTOOL_FORM, "Group|Tag Name|value", for values exiftool
# prints in another format (dates, coordinates), so the visibility check can
# tell "shown, reformatted" from "not shown".
printf 'string\tkind\tfile\tlocation\tgroup\ttier\tbasis\tencoding\texiftool_form\n' > "$REG"
canary() {
  local s
  s="CANARY-$1-$(printf '%s' "$1" | sha1sum | cut -c1-4)"
  printf '%s\tcanary\t%s\t%s\t%s\t%s\t%s\t%s\t\n' "$s" "$2" "$3" "$4" "$5" "$6" "${7:-raw}" >> "$REG"
  printf '%s' "$s"
}
marker() {
  printf '%s\tmarker\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' "$1" "$2" "$3" "$4" "$5" "$6" "${7:-raw}" "${8:-}" >> "$REG"
  printf '%s' "$1"
}

# exiftool wrapper: any warning or error stops the build.
CFG="$W/exiftool.config"
cat > "$CFG" <<'EOF'
# Lets the fixture builder write tags that exiftool would not write on its own:
# a raw MakerNote and two private tags with IDs no standard assigns.
%Image::ExifTool::UserDefined = (
  'Image::ExifTool::Exif::Main' => {
    0x927c => { Name => 'FixtureMakerNote',   Writable => 'undef',  WriteGroup => 'ExifIFD' },
    0xbeef => { Name => 'FixturePrivateIFD0', Writable => 'string', WriteGroup => 'IFD0' },
    0xbef0 => { Name => 'FixturePrivateExif', Writable => 'string', WriteGroup => 'ExifIFD' },
  },
);
1;
EOF
# Tags every camera writes. Without them exiftool creates ColorSpace
# "Uncalibrated" and copies the JFIF density (1 x 1, no unit) into IFD0.
cat > "$W/common.args" <<'EOF'
-XResolution=72
-YResolution=72
-ResolutionUnit=inches
-ExifIFD:ColorSpace#=1
EOF
et() {
  local err
  if ! err=$(exiftool -config "$CFG" -overwrite_original "$@" 2>&1 >/dev/null); then
    echo "make-fixtures: exiftool failed: $err" >&2; exit 1
  fi
  if [ -n "$err" ]; then echo "make-fixtures: exiftool warned: $err" >&2; exit 1; fi
}

# A colour profile from the system. Display P3 if one is installed, else sRGB.
ICC_SRC=""
for p in /usr/share/color/icc/*/*[Pp]3*.ic[cm] /usr/share/color/icc/colord/sRGB.icc /usr/share/color/icc/ghostscript/srgb.icc; do
  if [ -f "$p" ]; then ICC_SRC="$p"; break; fi
done
[ -n "$ICC_SRC" ] || { echo "make-fixtures: no ICC profile found under /usr/share/color/icc" >&2; exit 1; }

# Scenes. Drawn shapes only, no text, so fonts cannot change the output.
scene() { # OUT WIDTH HEIGHT SEED SKY GROUND
  local w=$2 h=$3
  magick -size "${w}x${h}" "gradient:$5-#f3e2c0" \
    -fill "$6" -draw "rectangle 0,$((h * 2 / 3)) $((w - 1)),$((h - 1))" \
    -fill '#f7d046' -draw "circle $((w / 5)),$((h / 5)) $((w / 5 + w / 17)),$((h / 5))" \
    -fill '#8b5a2b' -draw "rectangle $((w * 35 / 100)),$((h * 47 / 100)) $((w * 58 / 100)),$((h * 69 / 100))" \
    -fill '#b23a2e' -draw "polygon $((w * 33 / 100)),$((h * 47 / 100)) $((w * 465 / 1000)),$((h / 3)) $((w * 60 / 100)),$((h * 47 / 100))" \
    -seed "$4" -attenuate 0.25 +noise Gaussian -alpha off "$1"
}
jpg() { magick "$1" -strip -quality "${3:-90}" -sampling-factor 2x2 "$2"; }

echo "make-fixtures: ICC source $ICC_SRC; ffmpeg $([ "$USE_FFMPEG" = 1 ] && echo yes || echo no)"

# 1. jpeg-everything.jpg ######################################################
F=jpeg-everything.jpg
# The original scene has a red figure on the right. The main image is cropped
# so the figure is gone; both embedded previews still show it.
scene "$W/e-orig.png" 1200 900 11 '#9cc8ef' '#3f6b35'
magick "$W/e-orig.png" -fill '#e0301e' -draw 'circle 1060,500 1060,600' \
  -fill '#ffffff' -draw 'circle 1035,475 1035,488' -draw 'circle 1085,475 1085,488' "$W/e-orig.png"
magick "$W/e-orig.png" -crop 880x660+0+120 +repage "$W/e-main.png"
jpg "$W/e-main.png" "$W/e.jpg" 90
magick "$W/e-orig.png" -resize 160x120 -strip -quality 80 "$W/e-thumb.jpg"
et -Comment="$(canary JPEG-THUMB-COM "$F" 'EXIF IFD1 thumbnail (uncropped original), COM inside it' hidden red spec)" "$W/e-thumb.jpg"
magick "$W/e-orig.png" -resize 128x96 -strip -quality 75 "$W/e-psthumb.jpg"
et -Comment="$(canary JPEG-PSTHUMB-COM "$F" 'Photoshop IRB thumbnail (uncropped original), COM inside it' hidden red spec)" "$W/e-psthumb.jpg"
kit icc "$ICC_SRC" "$W/e.icc" "$(canary JPEG-ICC-PRIVATE "$F" 'ICC profile (APP2), private CNRY text tag' hidden red spec)"
kit blob "$W/e-makernote.bin" 240 7 "$(canary JPEG-EXIF-MAKERNOTE "$F" 'EXIF MakerNote (binary)' hidden red inferred)" 'FJORDCAM II'
cat > "$W/e.args" <<EOF
-ExifByteOrder=II
-Make=Fjordcam $(canary JPEG-EXIF-MAKE "$F" 'EXIF IFD0 Make' device amber spec)
-Model=F7 Pro $(canary JPEG-EXIF-MODEL "$F" 'EXIF IFD0 Model' device amber spec)
-Software=FjordOS 14.2.1 $(canary JPEG-EXIF-SOFTWARE "$F" 'EXIF IFD0 Software' device amber spec)
-Artist=Astrid Holmvik $(canary JPEG-EXIF-ARTIST "$F" 'EXIF IFD0 Artist' who red spec)
-Copyright=Copyright 2024 Astrid Holmvik $(canary JPEG-EXIF-COPYRIGHT "$F" 'EXIF IFD0 Copyright' who red spec)
-ImageDescription=Picnic below the tower $(canary JPEG-EXIF-DESCRIPTION "$F" 'EXIF IFD0 ImageDescription' hidden red inferred)
-ModifyDate=$(marker '2024:06:15 18:02:11' "$F" 'EXIF IFD0 DateTime (ModifyDate)' when amber spec)
-HostComputer=Astrid-Laptop $(canary JPEG-EXIF-HOSTCOMPUTER "$F" 'EXIF IFD0 HostComputer' who red spec)
-FixturePrivateIFD0=$(canary JPEG-EXIF-PRIVATE-IFD0 "$F" 'EXIF IFD0 unknown tag 0xBEEF' hidden red inferred)
-Orientation#=1
-XResolution=72
-YResolution=72
-ResolutionUnit=inches
-DateTimeOriginal=$(marker '2024:06:14 09:41:27' "$F" 'EXIF DateTimeOriginal' when amber spec)
-CreateDate=$(marker '2024:06:14 09:41:28' "$F" 'EXIF DateTimeDigitized (CreateDate)' when amber spec)
-OffsetTime=+02:00
-OffsetTimeOriginal=+02:00
-OffsetTimeDigitized=+02:00
-SubSecTimeOriginal=123
-SerialNumber=$(canary JPEG-EXIF-BODYSERIAL "$F" 'EXIF BodySerialNumber (exiftool: SerialNumber)' who red spec)
-LensSerialNumber=$(canary JPEG-EXIF-LENSSERIAL "$F" 'EXIF LensSerialNumber' who red spec)
-LensMake=Fjordcam
-LensModel=Fjordcam 6.9mm f/1.8 $(canary JPEG-EXIF-LENSMODEL "$F" 'EXIF LensModel' device amber spec)
-OwnerName=Jonas Brekkestad $(canary JPEG-EXIF-OWNER "$F" 'EXIF CameraOwnerName (exiftool: OwnerName)' who red spec)
-ImageUniqueID=$(canary JPEG-EXIF-UNIQUEID "$F" 'EXIF ImageUniqueID' hidden red spec)
-UserComment=Taken with the self timer $(canary JPEG-EXIF-USERCOMMENT "$F" 'EXIF UserComment' hidden red inferred)
-FixturePrivateExif=$(canary JPEG-EXIF-PRIVATE-EXIF "$F" 'EXIF Exif IFD unknown tag 0xBEF0' hidden red inferred)
-FixtureMakerNote<=$W/e-makernote.bin
-ExposureTime=1/250
-FNumber=1.8
-ISO=64
-FocalLength=6.9
-FocalLengthIn35mmFormat=24
-ExposureProgram#=2
-ExposureCompensation=0
-MeteringMode#=5
-ExifIFD:Flash#=16
-WhiteBalance#=0
-ColorSpace#=1
-ExifImageWidth=880
-ExifImageHeight=660
-InteropIndex=R98
-GPSLatitude=48.858370
-GPSLatitudeRef=N
-GPSLongitude=2.294481
-GPSLongitudeRef=E
-GPSAltitude=35
-GPSAltitudeRef#=0
-GPSImgDirection=312.5
-GPSImgDirectionRef=T
-GPSDateStamp=2024:06:14
-GPSTimeStamp=07:41:27
-GPSProcessingMethod=GPS
-GPSMapDatum=WGS-84
-GPSAreaInformation=Champ de Mars, Paris $(canary JPEG-GPS-AREA "$F" 'EXIF GPS IFD GPSAreaInformation' where red spec)
-ThumbnailImage<=$W/e-thumb.jpg
-XMP-dc:Creator=Astrid Holmvik $(canary JPEG-XMP-CREATOR "$F" 'XMP dc:creator' who red spec)
-XMP-xmp:CreatorTool=FjordOS Camera 14.2 $(canary JPEG-XMP-CREATORTOOL "$F" 'XMP xmp:CreatorTool' device amber spec)
-XMP-xmp:CreateDate=2024:06:14 09:41:27.456+02:00
-XMP-photoshop:City=Paris $(canary JPEG-XMP-CITY "$F" 'XMP photoshop:City' where red spec)
-XMP-xmpMM:DocumentID=xmp.did:$(canary JPEG-XMP-DOCUMENTID "$F" 'XMP xmpMM:DocumentID' hidden red spec)
-XMP-xmpMM:InstanceID=xmp.iid:$(canary JPEG-XMP-INSTANCEID "$F" 'XMP xmpMM:InstanceID' hidden red spec)
-XMP-xmpMM:History+={Action=created,When=2024:06:14 09:41:27+02:00,SoftwareAgent=FjordOS Camera 14.2}
-XMP-xmpMM:History+={Action=saved,When=2024:06:15 18:02:11+02:00,SoftwareAgent=Fjord Studio 3.1 $(canary JPEG-XMP-HISTORY "$F" 'XMP xmpMM:History stEvt:softwareAgent' hidden red spec),Changed=/}
-XMP-aux:SerialNumber=$(canary JPEG-XMP-AUXSERIAL "$F" 'XMP aux:SerialNumber' who red spec)
-XMP-exif:GPSLatitude=48.858370 N
-XMP-exif:GPSLongitude=2.294481 E
-IPTC:By-line=$(canary JPEG-IPTC-BYLINE "$F" 'IPTC By-line' who red spec)
-IPTC:City=Paris $(canary JPEG-IPTC-CITY "$F" 'IPTC City' where red spec)
-IPTC:Caption-Abstract=Sunday picnic $(canary JPEG-IPTC-CAPTION "$F" 'IPTC Caption-Abstract' hidden red inferred)
-IPTC:Keywords+=picnic
-IPTC:Keywords+=$(canary JPEG-IPTC-KEYWORD "$F" 'IPTC Keywords' hidden red inferred)
-IPTC:CopyrightNotice=(c) 2024 Astrid Holmvik $(canary JPEG-IPTC-COPYRIGHT "$F" 'IPTC CopyrightNotice' who red spec)
-PhotoshopThumbnail<=$W/e-psthumb.jpg
-Comment=Shot on a tripod $(canary JPEG-COM "$F" 'JPEG COM segment' hidden red inferred)
-Ducky:Quality=80
-Ducky:Comment=$(canary JPEG-DUCKY-COMMENT "$F" 'APP12 Ducky Comment (UTF-16)' hidden red inferred utf16)
-Ducky:Copyright=$(canary JPEG-DUCKY-COPYRIGHT "$F" 'APP12 Ducky Copyright (UTF-16)' who red spec utf16)
-ICC_Profile<=$W/e.icc
EOF
et -@ "$W/common.args" -@ "$W/e.args" "$W/e.jpg"
marker '48,51.5022N' "$F" 'XMP exif:GPSLatitude (as exiftool writes it)' where red spec raw "XMP-exif|GPS Latitude|48 deg 51' 30.13\" N" >/dev/null
marker '2024-06-14T09:41:27.456+02:00' "$F" 'XMP xmp:CreateDate' when amber spec raw 'XMP-xmp|Create Date|2024:06:14 09:41:27.456+02:00' >/dev/null
kit c2pa "$W/e-c2pa1.bin" "$W/e-c2pa2.bin" \
  "Astrid Holmvik $(canary JPEG-C2PA-AUTHOR "$F" 'APP11 C2PA, CreativeWork author (JUMBF segment 1)' hidden red spec)" \
  "FjordOS_Camera/14.2 $(canary JPEG-C2PA-GENERATOR "$F" 'APP11 C2PA, claim_generator in CBOR claim (JUMBF segment 2)' hidden red spec)"
kit blob "$W/e-app5.bin" 96 5 "$(canary JPEG-APP5 "$F" 'Unidentified APP5 segment, placed after DQT' hidden red inferred)" 'FJRD'
kit jpeg-insert "$W/e.jpg" "$W/e2.jpg" after:e2 "eb:$W/e-c2pa1.bin" "eb:$W/e-c2pa2.bin"
kit jpeg-insert "$W/e2.jpg" "$OUT/$F" before:c0 "e5:$W/e-app5.bin"

# 2. jpeg-orientation-6.jpg ###################################################
F=jpeg-orientation-6.jpg
# Drawn upright as a 480x640 portrait, then stored rotated 90 degrees anticlockwise
# as 640x480 with Orientation 6, the way a phone held upright stores it.
magick -size 480x640 xc:'#dddddd' \
  -fill '#d62828' -draw 'rectangle 0,0 119,119' \
  -fill '#2a9d3f' -draw 'rectangle 360,0 479,119' \
  -fill '#1d4ed8' -draw 'rectangle 180,520 299,639' \
  -fill '#222222' -draw 'polygon 240,160 330,300 270,300 270,460 210,460 210,300 150,300' \
  -seed 21 -attenuate 0.15 +noise Gaussian -rotate -90 "$W/o.png"
jpg "$W/o.png" "$W/o.jpg" 90
magick "$W/o.png" -resize 160x120 -strip -quality 80 "$W/o-thumb.jpg"
et -Comment="$(canary ORIENT-THUMB-COM "$F" 'EXIF IFD1 thumbnail, COM inside it' hidden red spec)" "$W/o-thumb.jpg"
cat > "$W/o.args" <<EOF
-ExifByteOrder=MM
-Orientation#=6
-Make=Fjordcam $(canary ORIENT-EXIF-MAKE "$F" 'EXIF IFD0 Make (big-endian EXIF)' device amber spec)
-Model=F5
-Artist=Astrid Holmvik $(canary ORIENT-EXIF-ARTIST "$F" 'EXIF IFD0 Artist' who red spec)
-SerialNumber=$(canary ORIENT-EXIF-BODYSERIAL "$F" 'EXIF BodySerialNumber' who red spec)
-DateTimeOriginal=$(marker '2023:11:02 15:20:44' "$F" 'EXIF DateTimeOriginal' when amber spec)
-OffsetTimeOriginal=+01:00
-ExifImageWidth=640
-ExifImageHeight=480
-GPSLatitude=52.516275
-GPSLatitudeRef=N
-GPSLongitude=13.377704
-GPSLongitudeRef=E
-GPSAltitude=34
-GPSAltitudeRef#=0
-ThumbnailImage<=$W/o-thumb.jpg
EOF
et -@ "$W/common.args" -@ "$W/o.args" "$W/o.jpg"
cp "$W/o.jpg" "$OUT/$F"

# 3. jpeg-progressive.jpg #####################################################
F=jpeg-progressive.jpg
scene "$W/p.png" 640 480 31 '#a8c5e6' '#6b7f3a'
magick "$W/p.png" -strip -interlace JPEG -quality 88 -sampling-factor 2x2 "$W/p.jpg"
cat > "$W/p.args" <<EOF
-Artist=Astrid Holmvik $(canary PROG-EXIF-ARTIST "$F" 'EXIF IFD0 Artist' who red spec)
-Software=Fjord Studio 3.1 $(canary PROG-EXIF-SOFTWARE "$F" 'EXIF IFD0 Software' device amber spec)
-DateTimeOriginal=$(marker '2023:05:20 11:12:13' "$F" 'EXIF DateTimeOriginal' when amber spec)
-GPSLatitude=41.890210
-GPSLatitudeRef=N
-GPSLongitude=12.492231
-GPSLongitudeRef=E
-GPSAreaInformation=Colosseo, Roma $(canary PROG-GPS-AREA "$F" 'EXIF GPS IFD GPSAreaInformation' where red spec)
-XMP-dc:Creator=Astrid Holmvik $(canary PROG-XMP-CREATOR "$F" 'XMP dc:creator' who red spec)
-Comment=$(canary PROG-COM "$F" 'JPEG COM segment' hidden red inferred)
EOF
et -@ "$W/common.args" -@ "$W/p.args" "$W/p.jpg"
cp "$W/p.jpg" "$OUT/$F"

# 4. jpeg-ultrahdr-like.jpg ###################################################
F=jpeg-ultrahdr-like.jpg
scene "$W/u.png" 800 600 41 '#7fb2e5' '#2f5d50'
jpg "$W/u.png" "$W/u.jpg" 90
cat > "$W/u.args" <<EOF
-Make=Fjordcam $(canary UHDR-EXIF-MAKE "$F" 'Primary image EXIF IFD0 Make' device amber spec)
-Model=F9 Pro
-Artist=Astrid Holmvik $(canary UHDR-EXIF-ARTIST "$F" 'Primary image EXIF IFD0 Artist' who red spec)
-DateTimeOriginal=$(marker '2025:01:26 20:15:30' "$F" 'Primary image EXIF DateTimeOriginal' when amber spec)
-GPSLatitude=33.856784
-GPSLatitudeRef=S
-GPSLongitude=151.215297
-GPSLongitudeRef=E
EOF
et -@ "$W/common.args" -@ "$W/u.args" "$W/u.jpg"
magick "$W/u.png" -colorspace Gray -resize 200x150 -strip -quality 85 "$W/u-gain-bare.jpg"
cat > "$W/u-gain.xml" <<EOF
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Fjord XMP Core 1.0">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:hdrgm="http://ns.adobe.com/hdr-gain-map/1.0/"
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    hdrgm:Version="1.0" hdrgm:GainMapMin="0" hdrgm:GainMapMax="2.3" hdrgm:Gamma="1"
    hdrgm:OffsetSDR="0.015625" hdrgm:OffsetHDR="0.015625"
    hdrgm:HDRCapacityMin="0" hdrgm:HDRCapacityMax="2.3" hdrgm:BaseRenditionIsHDR="False">
   <dc:creator><rdf:Seq><rdf:li>Astrid Holmvik $(canary UHDR-GAINMAP-XMP-CREATOR "$F" 'Gain map (second JPEG after EOI, found through MPF): its own XMP dc:creator' who red spec)</rdf:li></rdf:Seq></dc:creator>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
EOF
kit xmp-payload "$W/u-gain.xml" "$W/u-gain-xmp.bin"
kit jpeg-insert "$W/u-gain-bare.jpg" "$W/u-gain.jpg" after:e0 "e1:$W/u-gain-xmp.bin"
GAIN_LEN=$(stat -c %s "$W/u-gain.jpg")
cat > "$W/u-primary.xml" <<EOF
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Fjord XMP Core 1.0">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:hdrgm="http://ns.adobe.com/hdr-gain-map/1.0/"
    xmlns:Container="http://ns.google.com/photos/1.0/container/"
    xmlns:Item="http://ns.google.com/photos/1.0/container/item/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    hdrgm:Version="1.0"
    xmp:CreatorTool="FjordOS HDR 2.0 $(canary UHDR-XMP-CREATORTOOL "$F" 'Primary image XMP xmp:CreatorTool' device amber spec)">
   <Container:Directory>
    <rdf:Seq>
     <rdf:li rdf:parseType="Resource">
      <Container:Item Item:Semantic="Primary" Item:Mime="image/jpeg"/>
     </rdf:li>
     <rdf:li rdf:parseType="Resource">
      <Container:Item Item:Semantic="GainMap" Item:Mime="image/jpeg" Item:Length="$GAIN_LEN"/>
     </rdf:li>
    </rdf:Seq>
   </Container:Directory>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
EOF
kit xmp-payload "$W/u-primary.xml" "$W/u-primary-xmp.bin"
kit jpeg-insert "$W/u.jpg" "$W/u2.jpg" after:e1 "e1:$W/u-primary-xmp.bin"
kit mpf "$W/u2.jpg" "$W/u-gain.jpg" "$OUT/$F" after:e1

# 4b. Ultra HDR variants #####################################################
# The gain map of these pictures starts unticked, so each keeps it and hides one
# thing in or around it that the page must still list and remove (or, for
# iso-full and zero-pad, nothing at all: they check that a clean gain map and
# zero padding survive untouched). Built from plain JPEGs with no other
# metadata, so each file carries only its own planted strings. The gain map has
# the full hdrgm description; the photo has hdrgm:Version, a Container directory
# and an MPF index (little-endian with image IDs and layout details in mpf-extras).
jpg "$W/u.png" "$W/uv.jpg" 90
uhdr() { local f=$1 kind=$2; shift 2; kit uhdr "$W/uv.jpg" "$W/u-gain-bare.jpg" "$OUT/$f" "$kind" "$@"; }
F=jpeg-uhdr-hdrgm-extra.jpg
uhdr "$F" hdrgm-extra "$(canary UHDRV-HDRGM-SERIAL "$F" 'Photo XMP, unknown hdrgm:CameraSerialNumber next to the gain map fields' who red spec)" \
  "$(canary UHDRV-HDRGM-GPS "$F" 'Photo XMP, unknown hdrgm:GPSLatitude next to the gain map fields' where red spec)"
F=jpeg-uhdr-item-label.jpg
uhdr "$F" item-label "$(canary UHDRV-ITEM-LABEL "$F" 'Photo XMP, Item:Label on the GainMap entry of the Container directory' hidden red spec)"
F=jpeg-uhdr-apple-owner.jpg
uhdr "$F" apple-owner "$(canary UHDRV-APPLE-OWNER "$F" 'Photo XMP, HDRGainMap:OwnerName next to HDRGainMap:HDRGainMapVersion' who red spec)"
F=jpeg-uhdr-after-eoi.jpg
uhdr "$F" after-eoi "$(canary UHDRV-AFTER-EOI "$F" 'Bytes after the gain map end marker, inside its MPF size (the gain map also has an XMP toolkit name)' hidden red spec)"
F=jpeg-uhdr-bare-after-eoi.jpg
uhdr "$F" bare-after-eoi "$(canary UHDRV-BARE-AFTER-EOI "$F" 'Bytes after the end marker of a gain map with no other metadata, inside its MPF size' hidden red spec)"
F=jpeg-uhdr-mpf-tail.jpg
uhdr "$F" mpf-tail "$(canary UHDRV-MPF-TAIL "$F" 'MPF APP2, bytes after the MP entry table that no structure uses' hidden red spec)"
F=jpeg-uhdr-inner-hdrgm.jpg
uhdr "$F" inner-hdrgm "$(canary UHDRV-INNER-HDRGM "$F" 'Gain map XMP, unknown hdrgm:CameraSerialNumber' who red spec)"
F=jpeg-uhdr-iso-tail.jpg
uhdr "$F" iso-tail "$(canary UHDRV-ISO-TAIL "$F" 'Photo ISO 21496-1 APP2, bytes after its version field' hidden red spec)"
F=jpeg-uhdr-inner-mpf.jpg
uhdr "$F" inner-mpf "$(canary UHDRV-INNER-MPF "$F" 'Gain map, an MPF APP2 segment of its own with a tail' hidden red spec)"
F=jpeg-uhdr-inner-iso.jpg
uhdr "$F" inner-iso "$(canary UHDRV-INNER-ISO "$F" 'Gain map ISO 21496-1 APP2, bytes after its version field' hidden red spec)"
F=jpeg-uhdr-version-text.jpg
uhdr "$F" version-text "$(canary UHDRV-VERSION-TEXT "$F" 'Photo XMP, text inside the value of hdrgm:Version' hidden red spec)"
F=jpeg-uhdr-mpf-extras.jpg
uhdr "$F" mpf-extras "$(canary UHDRV-MPF-UID "$F" 'MPF APP2 (little-endian), B003 ImageUIDList of the photo' hidden red spec)" \
  "$(canary UHDRV-MPF-ATTR-TAG "$F" 'MPF APP2, unknown ASCII tag B2EE in the MP Attribute IFD' hidden red spec)"
F=jpeg-uhdr-dir-semantic.jpg
uhdr "$F" dir-semantic "$(canary UHDRV-DIR-SEMANTIC "$F" 'Photo XMP, Item:Semantic of a third Container directory entry that stands for no part' hidden red spec)"
F=jpeg-uhdr-dir-mime.jpg
uhdr "$F" dir-mime "$(canary UHDRV-DIR-MIME "$F" 'Photo XMP, Item:Mime of the GainMap entry of the Container directory' hidden red spec)"
F=jpeg-uhdr-inner-gpano.jpg
uhdr "$F" inner-gpano "$(canary UHDRV-INNER-GPANO "$F" 'Gain map XMP, a name in GPano:Note (a technical namespace)' hidden red spec)"
uhdr jpeg-uhdr-iso-full.jpg iso-full
uhdr jpeg-uhdr-zero-pad.jpg zero-pad
# iPhone-style HDR: the gain map, its apdi:AuxiliaryImageType and the two HDR numbers of
# the MakerNote stay; the rest of the MakerNote and any other apdi field go.
F=jpeg-uhdr-apple.jpg
uhdr "$F" apple "$(canary UHDRV-APPLE-MAKERNOTE "$F" 'Photo EXIF, Apple MakerNote text tag 0x000B next to the HDR numbers (tags 33 and 48)' hidden red spec)" \
  "$(canary UHDRV-APPLE-APDI "$F" 'Gain map XMP, text in apdi:StoredFormat (an apdi field a gain map does not need)' hidden red spec)"
F=jpeg-uhdr-apple-wrong.jpg
uhdr "$F" apple-wrong "$(canary UHDRV-APPLE-AUXTYPE "$F" 'Gain map XMP, text after the fixed value of apdi:AuxiliaryImageType' hidden red spec)"
F=jpeg-uhdr-not-gainmap.jpg
uhdr "$F" not-gainmap "$(canary UHDRV-NOT-GAINMAP "$F" 'COM in a full-size colour second picture listed by MPF as type 0, with hdrgm in the photo XMP' hidden red spec)"

# 5. jpeg-motion-photo.jpg ####################################################
F=jpeg-motion-photo.jpg
scene "$W/m.png" 640 480 51 '#bcd7f0' '#4d6b3c'
jpg "$W/m.png" "$W/m.jpg" 90
cat > "$W/m.args" <<EOF
-Make=Fjordcam $(canary MOTION-EXIF-MAKE "$F" 'Still image EXIF IFD0 Make' device amber spec)
-Model=F9 Pro
-Artist=Astrid Holmvik $(canary MOTION-EXIF-ARTIST "$F" 'Still image EXIF IFD0 Artist' who red spec)
-DateTimeOriginal=$(marker '2025:07:04 17:45:12' "$F" 'Still image EXIF DateTimeOriginal' when amber spec)
-GPSLatitude=40.689247
-GPSLatitudeRef=N
-GPSLongitude=74.044502
-GPSLongitudeRef=W
EOF
et -@ "$W/common.args" -@ "$W/m.args" "$W/m.jpg"
M_XYZ=$(marker '+40.6892-074.0445+010.000/' "$F" 'Appended MP4: moov/udta/©xyz (QuickTime ISO 6709 location)' where red spec)
M_PLACE="Liberty Island $(canary MOTION-MP4-LOCI-NAME "$F" 'Appended MP4: moov/udta/loci place name (3GPP location box)' where red spec)"
M_TITLE=$(canary MOTION-MP4-TITLE "$F" 'Appended MP4: moov/udta/meta/ilst/©nam (title)' hidden red inferred)
M_COMMENT=$(canary MOTION-MP4-COMMENT "$F" 'Appended MP4: moov/udta/meta/ilst/©cmt (comment)' hidden red inferred)
if [ "$USE_FFMPEG" = 1 ]; then
  ffmpeg -nostdin -v error -y -f lavfi -i testsrc2=size=320x240:rate=15:duration=1 \
    -c:v mpeg4 -q:v 6 -pix_fmt yuv420p -fflags +bitexact -flags:v +bitexact -map_metadata -1 \
    -metadata title="$M_TITLE" -metadata comment="$M_COMMENT" "$W/m-raw.mp4"
  kit mp4-udta "$W/m-raw.mp4" "$W/m.mp4" "$M_XYZ" "$M_PLACE" 40.689247 -74.044502 10
else
  kit mp4-minimal "$W/m.mp4" "$M_XYZ" "$M_PLACE" 40.689247 -74.044502 10 "$M_TITLE" "$M_COMMENT"
fi
MP4_LEN=$(stat -c %s "$W/m.mp4")
cat > "$W/m.xml" <<EOF
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Fjord XMP Core 1.0">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:GCamera="http://ns.google.com/photos/1.0/camera/"
    xmlns:Container="http://ns.google.com/photos/1.0/container/"
    xmlns:Item="http://ns.google.com/photos/1.0/container/item/"
    GCamera:MotionPhoto="1"
    GCamera:MotionPhotoVersion="1"
    GCamera:MotionPhotoPresentationTimestampUs="500000">
   <Container:Directory>
    <rdf:Seq>
     <rdf:li rdf:parseType="Resource">
      <Container:Item Item:Mime="image/jpeg" Item:Semantic="Primary" Item:Length="0" Item:Padding="0"/>
     </rdf:li>
     <rdf:li rdf:parseType="Resource">
      <Container:Item Item:Mime="video/mp4" Item:Semantic="MotionPhoto" Item:Length="$MP4_LEN" Item:Padding="0"/>
     </rdf:li>
    </rdf:Seq>
   </Container:Directory>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
EOF
kit xmp-payload "$W/m.xml" "$W/m-xmp.bin"
kit jpeg-insert "$W/m.jpg" "$W/m2.jpg" after:e1 "e1:$W/m-xmp.bin"
cat "$W/m2.jpg" "$W/m.mp4" > "$OUT/$F"

# 6. jpeg-samsung-trailer.jpg #################################################
F=jpeg-samsung-trailer.jpg
scene "$W/s.png" 640 480 61 '#9fc3e0' '#55703f'
jpg "$W/s.png" "$W/s.jpg" 90
cat > "$W/s.args" <<EOF
-Make=samsung
-Model=SM-S9X1B $(canary SEF-EXIF-MODEL "$F" 'EXIF IFD0 Model' device amber spec)
-DateTimeOriginal=$(marker '2025:02:11 07:30:05' "$F" 'EXIF DateTimeOriginal' when amber spec)
-GPSLatitude=22.951916
-GPSLatitudeRef=S
-GPSLongitude=43.210487
-GPSLongitudeRef=W
EOF
et -@ "$W/common.args" -@ "$W/s.args" "$W/s.jpg"
kit samsung "$W/s-trailer.bin" \
  "$(marker 1739269805123 "$F" 'Samsung trailer block 0x0a01 Image_UTC_Data (ms since 1970, UTC)' when amber spec raw 'Samsung|Time Stamp|2025:02:11 10:30:05.123+00:00')" \
  724 \
  "{\"originalPath\":\"/storage/emulated/0/DCIM/Camera/20250211_073005.jpg\",\"reEditId\":\"$(canary SEF-TRAILER-REEDIT "$F" 'Samsung trailer block 0x0be1 Photo_Editor_Re_Edit_Data' hidden red inferred)\"}"
cat "$W/s.jpg" "$W/s-trailer.bin" > "$OUT/$F"

# 7. jpeg-extended-xmp.jpg ####################################################
F=jpeg-extended-xmp.jpg
scene "$W/x.png" 400 300 71 '#b0cde8' '#5a7a45'
jpg "$W/x.png" "$W/x.jpg" 88
X_EARLY=$(canary XXMP-EXT-ANCESTOR-500 "$F" 'Extended XMP (APP1 xmp/extension chunks), photoshop:DocumentAncestors item 500' hidden red spec)
X_LATE=$(canary XXMP-EXT-ANCESTOR-1800 "$F" 'Extended XMP, photoshop:DocumentAncestors item 1800 (past exiftool 1000-item limit)' hidden red spec)
X_CREATOR=$(canary XXMP-STD-CREATOR "$F" 'Standard XMP dc:creator' who red spec)
python3 - "$X_EARLY" "$X_LATE" "$X_CREATOR" > "$W/x.xmp" <<'EOF'
import sys
early, late, creator = sys.argv[1:4]
items = []
for i in range(2500):
    uid = 'xmp.did:%08x-%04x-4%03x-8%03x-%012x' % (0x5eed0000 + i, i * 7 % 0x10000, i % 0x1000, (i * 3) % 0x1000, i * 7919)
    if i == 500:
        uid = 'xmp.did:' + early
    if i == 1800:
        uid = 'xmp.did:' + late
    items.append('<rdf:li>%s</rdf:li>' % uid)
print('<?xpacket begin="﻿" id="W5M0MpCehiHzreSzNTczkc9d"?>')
print('<x:xmpmeta xmlns:x="adobe:ns:meta/"><rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">'
      '<rdf:Description rdf:about="" xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/">'
      '<dc:creator><rdf:Seq><rdf:li>Astrid Holmvik %s</rdf:li></rdf:Seq></dc:creator>'
      '<photoshop:DocumentAncestors><rdf:Bag>%s</rdf:Bag></photoshop:DocumentAncestors>'
      '</rdf:Description></rdf:RDF></x:xmpmeta>' % (creator, ''.join(items)))
print('<?xpacket end="w"?>')
EOF
# -m lets exiftool copy all 2500 list items (it stops at 1000 otherwise).
et -m -tagsfromfile "$W/x.xmp" '-xmp:all' "$W/x.jpg"
cp "$W/x.jpg" "$OUT/$F"

# 8. png-everything.png #######################################################
F=png-everything.png
scene "$W/g.png" 480 360 81 '#a3c4e3' '#466b3b'
magick "$W/g.png" -strip "PNG24:$W/g-base.png"
kit icc "$ICC_SRC" "$W/g.icc" "$(canary PNG-ICCP-PRIVATE "$F" 'iCCP profile (compressed), private CNRY text tag' hidden red spec zlib)"
magick -size 8x8 xc:gray -strip "$W/g-exif-carrier.jpg"
cat > "$W/g-exif.args" <<EOF
-ExifByteOrder=MM
-Artist=Astrid Holmvik $(canary PNG-EXIF-ARTIST "$F" 'eXIf chunk, IFD0 Artist' who red spec)
-Software=Fjord Studio 3.1 $(canary PNG-EXIF-SOFTWARE "$F" 'eXIf chunk, IFD0 Software' device amber spec)
-GPSLatitude=51.500729
-GPSLatitudeRef=N
-GPSLongitude=0.124625
-GPSLongitudeRef=W
EOF
et -@ "$W/common.args" -@ "$W/g-exif.args" "$W/g-exif-carrier.jpg"
kit jpeg-exif "$W/g-exif-carrier.jpg" "$W/g-exif.tif"
magick -size 8x8 xc:gray -strip "$W/g-raw-carrier.jpg"
cat > "$W/g-raw.args" <<EOF
-ExifByteOrder=II
-Artist=Astrid Holmvik $(canary PNG-RAWEXIF-ARTIST "$F" 'tEXt "Raw profile type exif" (hex), IFD0 Artist' who red spec hex)
-GPSLatitude=51.500729
-GPSLatitudeRef=N
-GPSLongitude=0.124625
-GPSLongitudeRef=W
EOF
et -@ "$W/common.args" -@ "$W/g-raw.args" "$W/g-raw-carrier.jpg"
kit jpeg-exif "$W/g-raw-carrier.jpg" "$W/g-raw.tif"
cat > "$W/g.xml" <<EOF
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Fjord XMP Core 1.0">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmp:CreatorTool="Fjord Studio 3.1 $(canary PNG-XMP-CREATORTOOL "$F" 'iTXt XML:com.adobe.xmp, xmp:CreatorTool' device amber spec)"
    xmp:CreateDate="$(marker '2024-07-21T14:03:09+01:00' "$F" 'iTXt XMP xmp:CreateDate' when amber spec raw 'XMP-xmp|Create Date|2024:07:21 14:03:09+01:00')"
    xmpMM:DocumentID="xmp.did:$(canary PNG-XMP-DOCUMENTID "$F" 'iTXt XMP xmpMM:DocumentID' hidden red spec)"
    photoshop:City="London $(canary PNG-XMP-CITY "$F" 'iTXt XMP photoshop:City' where red spec)"
    exif:GPSLatitude="$(marker '51,30.04374N' "$F" 'iTXt XMP exif:GPSLatitude' where red spec raw "XMP-exif|GPS Latitude|51 deg 30' 2.62\" N")"
    exif:GPSLongitude="0,7.47750W">
   <dc:creator><rdf:Seq><rdf:li>Astrid Holmvik $(canary PNG-XMP-CREATOR "$F" 'iTXt XMP dc:creator' who red spec)</rdf:li></rdf:Seq></dc:creator>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
EOF
kit xpacket "$W/g.xml" "$W/g.xmp"
cat > "$W/g.json" <<EOF
{
  "base": "$W/g-base.png",
  "out": "$OUT/$F",
  "idat_split": 16384,
  "before": [
    {"type": "iCCP", "name": "Fjord sRGB $(canary PNG-ICCP-NAME "$F" 'iCCP profile name field' hidden red spec)", "file": "g.icc"},
    {"type": "pHYs", "value": [2835, 2835, 1]},
    {"type": "eXIf", "file": "g-exif.tif"},
    {"type": "tEXt", "keyword": "Author", "text": "Astrid Holmvik $(canary PNG-TEXT-AUTHOR "$F" 'tEXt Author' who red spec)"},
    {"type": "tEXt", "keyword": "Creation Time", "text": "$(marker 'Sun, 21 Jul 2024 14:03:09 +0100' "$F" 'tEXt Creation Time' when amber spec raw 'PNG|Creation Time|2024:07:21 14:03:09+01:00')"},
    {"type": "tEXt", "keyword": "Software", "text": "Fjord Studio 3.1 $(canary PNG-TEXT-SOFTWARE "$F" 'tEXt Software' device amber spec)"},
    {"type": "iTXt", "keyword": "XML:com.adobe.xmp", "file": "g.xmp"},
    {"type": "rawprofile", "name": "exif", "file": "g-raw.tif"},
    {"type": "raw", "chunk": "prVt", "text": "fjord-private-v1;$(canary PNG-PRVT "$F" 'Unknown ancillary chunk prVt' hidden red inferred)"}
  ],
  "after": [
    {"type": "tEXt", "keyword": "Comment", "text": "Exported for the family album $(canary PNG-TEXT-COMMENT "$F" 'tEXt Comment, after IDAT' hidden red inferred)"},
    {"type": "zTXt", "keyword": "Description", "text": "Evening by the river $(canary PNG-ZTXT-DESCRIPTION "$F" 'zTXt Description (compressed), after IDAT' hidden red inferred zlib)"},
    {"type": "iTXt", "keyword": "Title", "lang": "nb-NO", "translated": "Tittel", "compressed": true, "text": "Kveld ved elva $(canary PNG-ITXT-TITLE "$F" 'iTXt Title, nb-NO, compressed, after IDAT' hidden red inferred zlib)"},
    {"type": "tIME", "value": [2024, 7, 21, 13, 3, 9]}
  ],
  "trailer": "FJORD-TRAILER-V1 $(canary PNG-AFTER-IEND "$F" 'Bytes after IEND' hidden red inferred)\n"
}
EOF
kit png-build "$W/g.json"

# 9. png-transparent.png ######################################################
F=png-transparent.png
# Opaque centre, a soft semi-transparent ring and fully transparent corners.
magick -size 400x300 radial-gradient:white-black -level 25%,75% "$W/t-alpha.png"
magick -size 400x300 gradient:'#ff7a18'-'#7a1fa2' \
  -fill '#ffffff' -draw 'circle 200,150 200,190' "$W/t-colour.png"
magick "$W/t-colour.png" "$W/t-alpha.png" -alpha off -compose CopyOpacity -composite -strip "PNG32:$W/t-base.png"
cat > "$W/t.json" <<EOF
{
  "base": "$W/t-base.png",
  "out": "$OUT/$F",
  "before": [
    {"type": "tEXt", "keyword": "Author", "text": "Astrid Holmvik $(canary PNGA-TEXT-AUTHOR "$F" 'tEXt Author' who red spec)"},
    {"type": "tEXt", "keyword": "Software", "text": "Fjord Studio 3.1 $(canary PNGA-TEXT-SOFTWARE "$F" 'tEXt Software' device amber spec)"}
  ]
}
EOF
kit png-build "$W/t.json"

# 10. webp-everything.webp ####################################################
F=webp-everything.webp
scene "$W/w.png" 480 360 101 '#a9cbe8' '#4a6e40'
magick "$W/w.png" -strip -quality 80 -define webp:lossless=false -define webp:method=4 "$W/w-base.webp"
kit icc "$ICC_SRC" "$W/w.icc" "$(canary WEBP-ICCP-PRIVATE "$F" 'ICCP chunk, private CNRY text tag' hidden red spec)"
magick -size 8x8 xc:gray -strip "$W/w-exif-carrier.jpg"
cat > "$W/w-exif.args" <<EOF
-ExifByteOrder=II
-Make=Fjordcam $(canary WEBP-EXIF-MAKE "$F" 'EXIF chunk, IFD0 Make' device amber spec)
-Artist=Astrid Holmvik $(canary WEBP-EXIF-ARTIST "$F" 'EXIF chunk, IFD0 Artist' who red spec)
-DateTimeOriginal=$(marker '2024:09:08 12:34:56' "$F" 'EXIF chunk, DateTimeOriginal' when amber spec)
-GPSLatitude=41.403629
-GPSLatitudeRef=N
-GPSLongitude=2.174356
-GPSLongitudeRef=E
EOF
et -@ "$W/common.args" -@ "$W/w-exif.args" "$W/w-exif-carrier.jpg"
kit jpeg-exif "$W/w-exif-carrier.jpg" "$W/w-exif.tif"
cat > "$W/w.xml" <<EOF
<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Fjord XMP Core 1.0">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:dc="http://purl.org/dc/elements/1.1/"
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:xmpMM="http://ns.adobe.com/xap/1.0/mm/"
    xmlns:exif="http://ns.adobe.com/exif/1.0/"
    xmp:CreatorTool="Fjord Studio 3.1 $(canary WEBP-XMP-CREATORTOOL "$F" 'XMP chunk, xmp:CreatorTool' device amber spec)"
    xmpMM:DocumentID="xmp.did:$(canary WEBP-XMP-DOCUMENTID "$F" 'XMP chunk, xmpMM:DocumentID' hidden red spec)"
    exif:GPSLatitude="$(marker '41,24.21774N' "$F" 'XMP chunk, exif:GPSLatitude' where red spec raw "XMP-exif|GPS Latitude|41 deg 24' 13.06\" N")"
    exif:GPSLongitude="2,10.46136E">
   <dc:creator><rdf:Seq><rdf:li>Astrid Holmvik $(canary WEBP-XMP-CREATOR "$F" 'XMP chunk, dc:creator' who red spec)</rdf:li></rdf:Seq></dc:creator>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>
EOF
kit xpacket "$W/w.xml" "$W/w.xmp" odd
cat > "$W/w.json" <<EOF
{
  "base": "$W/w-base.webp",
  "out": "$OUT/$F",
  "icc": "$W/w.icc",
  "exif": "$W/w-exif.tif",
  "xmp": "$W/w.xmp",
  "unknown": [["PRVT", "fjord-private-v1;$(canary WEBP-PRVT "$F" 'Unknown RIFF chunk PRVT' hidden red inferred)"]]
}
EOF
kit webp-build "$W/w.json"

# 11. heic-everything.heic ####################################################
F=heic-everything.heic
scene "$W/h.png" 640 480 111 '#9ec0e2' '#3d6a46'
magick "$W/h.png" -strip -depth 8 -quality 60 "$W/h.heic"
magick "$W/h.png" -resize 160x120 -strip -quality 80 "$W/h-thumb.jpg"
et -Comment="$(canary HEIC-THUMB-COM "$F" 'EXIF IFD1 thumbnail, COM inside it' hidden red spec)" "$W/h-thumb.jpg"
cat > "$W/h.args" <<EOF
-Make=Fjordcam $(canary HEIC-EXIF-MAKE "$F" 'EXIF item, IFD0 Make' device amber spec)
-Model=F9 Pro $(canary HEIC-EXIF-MODEL "$F" 'EXIF item, IFD0 Model' device amber spec)
-Artist=Astrid Holmvik $(canary HEIC-EXIF-ARTIST "$F" 'EXIF item, IFD0 Artist' who red spec)
-SerialNumber=$(canary HEIC-EXIF-BODYSERIAL "$F" 'EXIF item, BodySerialNumber' who red spec)
-DateTimeOriginal=$(marker '2024:04:12 16:20:00' "$F" 'EXIF item, DateTimeOriginal' when amber spec)
-OffsetTimeOriginal=-07:00
-GPSLatitude=37.819929
-GPSLatitudeRef=N
-GPSLongitude=122.478255
-GPSLongitudeRef=W
-GPSAltitude=67
-GPSAltitudeRef#=0
-ThumbnailImage<=$W/h-thumb.jpg
-XMP-dc:Creator=Astrid Holmvik $(canary HEIC-XMP-CREATOR "$F" 'XMP item, dc:creator' who red spec)
-XMP-xmp:CreatorTool=FjordOS Camera 14.2 $(canary HEIC-XMP-CREATORTOOL "$F" 'XMP item, xmp:CreatorTool' device amber spec)
EOF
et -@ "$W/common.args" -@ "$W/h.args" "$W/h.heic"
cp "$W/h.heic" "$OUT/$F"

# 12. jpeg-large.jpg ##########################################################
F=jpeg-large.jpg
# 6000 x 4000, gradient plus plasma plus noise, so it compresses like a photo.
magick -seed 4242 -size 6000x4000 gradient:'#87a9d8'-'#3b5d2a' \
  \( -size 1500x1000 plasma:'#996644'-'#88aa66' -resize '6000x4000!' \) \
  -compose overlay -composite -attenuate 0.35 +noise Gaussian \
  -strip -quality 92 -sampling-factor 2x2 "$W/l.jpg"
cat > "$W/l.args" <<EOF
-Make=Fjordcam $(canary LARGE-EXIF-MAKE "$F" 'EXIF IFD0 Make' device amber spec)
-Model=F9 Pro
-Artist=Astrid Holmvik $(canary LARGE-EXIF-ARTIST "$F" 'EXIF IFD0 Artist' who red spec)
-DateTimeOriginal=$(marker '2023:08:19 06:58:41' "$F" 'EXIF DateTimeOriginal' when amber spec)
-GPSLatitude=13.163141
-GPSLatitudeRef=S
-GPSLongitude=72.544963
-GPSLongitudeRef=W
-GPSAltitude=2430
-GPSAltitudeRef#=0
-GPSAreaInformation=Machu Picchu $(canary LARGE-GPS-AREA "$F" 'EXIF GPS IFD GPSAreaInformation' where red spec)
EOF
et -@ "$W/common.args" -@ "$W/l.args" "$W/l.jpg"
cp "$W/l.jpg" "$OUT/$F"

# 13. not-an-image.pdf and truncated.jpg ######################################
F=not-an-image.pdf
kit pdf "$OUT/$F" \
  "Astrid Holmvik $(canary PDF-INFO-AUTHOR "$F" 'PDF Info dictionary /Author' who red inferred)" \
  "Board notes $(canary PDF-INFO-TITLE "$F" 'PDF Info dictionary /Title' hidden red inferred)"
F=truncated.jpg
scene "$W/r.png" 320 240 131 '#a0c4e4' '#4f7040'
jpg "$W/r.png" "$W/r.jpg" 90
et -Artist="Astrid Holmvik $(canary TRUNC-EXIF-ARTIST "$F" 'EXIF IFD0 Artist (file cut off at 2,048 bytes, inside the scan data)' who red spec)" "$W/r.jpg"
SOS=$(kit sos-offset "$W/r.jpg")
[ "$SOS" -lt 2048 ] && [ "$(stat -c %s "$W/r.jpg")" -gt 4096 ] || { echo "make-fixtures: truncated.jpg would not cut inside the scan" >&2; exit 1; }
head -c 2048 "$W/r.jpg" > "$OUT/$F"

# 14. Extra hostile structures ################################################
# jpeg-double-exif.jpg: two EXIF APP1 segments. Many readers stop at the first,
# so GPS and a second Artist hide in the second.
F=jpeg-double-exif.jpg
scene "$W/d.png" 320 240 141 '#a7c7e7' '#527347'
jpg "$W/d.png" "$W/d.jpg" 90
cp "$W/d.jpg" "$W/d-first.jpg"
cp "$W/d.jpg" "$W/d-second.jpg"
et -@ "$W/common.args" -ExifByteOrder=II -Make="Fjordcam $(canary DBLEXIF-FIRST-MAKE "$F" 'First EXIF APP1, IFD0 Make' device amber spec)" \
   -Artist="Astrid Holmvik $(canary DBLEXIF-FIRST-ARTIST "$F" 'First EXIF APP1, IFD0 Artist' who red spec)" "$W/d-first.jpg"
cat > "$W/d-second.args" <<EOF
-ExifByteOrder=MM
-Artist=Jonas Brekkestad $(canary DBLEXIF-SECOND-ARTIST "$F" 'Second EXIF APP1, IFD0 Artist' who red spec)
-GPSLatitude=51.505456
-GPSLatitudeRef=N
-GPSLongitude=0.075356
-GPSLongitudeRef=W
-GPSAreaInformation=Tower Bridge $(canary DBLEXIF-SECOND-GPS-AREA "$F" 'Second EXIF APP1, GPS GPSAreaInformation' where red spec)
EOF
et -@ "$W/common.args" -@ "$W/d-second.args" "$W/d-second.jpg"
kit jpeg-segment "$W/d-first.jpg" "$W/d-exif1.bin" e1 Exif
kit jpeg-segment "$W/d-second.jpg" "$W/d-exif2.bin" e1 Exif
kit jpeg-insert "$W/d.jpg" "$OUT/$F" after:e0 "e1:$W/d-exif1.bin" "e1:$W/d-exif2.bin"

# jpeg-ifd-cycle.jpg and jpeg-ifd-overflow.jpg: TIFF structures that loop or
# point outside the segment. A parser must stop, not hang or allocate gigabytes.
for kind in cycle overflow; do
  F=jpeg-ifd-$kind.jpg
  scene "$W/$kind.png" 320 240 151 '#a5c6e6' '#507245'
  jpg "$W/$kind.png" "$W/$kind.jpg" 90
  KIND_UP=$(printf '%s' "$kind" | tr '[:lower:]' '[:upper:]')
  kit hostile-exif "$kind" "$W/$kind-exif.bin" \
    "Astrid Holmvik $(canary "$KIND_UP-EXIF-ARTIST" "$F" "EXIF IFD0 Artist, the one well-formed tag in a hostile IFD ($kind)" who red spec)"
  kit jpeg-insert "$W/$kind.jpg" "$OUT/$F" after:e0 "e1:$W/$kind-exif.bin"
done

# 15. Free text in green details ##############################################
# A colour profile and a technical XMP field are green and kept by default, so a
# name hidden in them must be offered as its own red detail and go by default,
# with the colours unchanged.
F=jpeg-icc-text.jpg
scene "$W/it.png" 320 240 161 '#a8c8e6' '#4c6f42'
jpg "$W/it.png" "$W/it.jpg" 90
kit icc-text "$ICC_SRC" "$W/it.icc" mluc \
  "desc=Astrid Holmvik $(canary ICCTEXT-JPEG-DESC "$F" 'ICC profile (APP2), mluc description' hidden red spec utf16)" \
  "cprt=Copyright Astrid Holmvik $(canary ICCTEXT-JPEG-CPRT "$F" 'ICC profile (APP2), mluc copyright' hidden red spec utf16)" \
  "dmnd=Astrid Holmvik $(canary ICCTEXT-JPEG-DMND "$F" 'ICC profile (APP2), mluc device manufacturer description' hidden red spec utf16)"
et "-ICC_Profile<=$W/it.icc" "$W/it.jpg"
cp "$W/it.jpg" "$OUT/$F"

F=png-icc-text.png
magick "$W/it.png" -strip "PNG24:$W/ip-base.png"
kit icc-text "$ICC_SRC" "$W/ip.icc" ascii \
  "desc=Astrid Holmvik $(canary ICCTEXT-PNG-DESC "$F" 'iCCP profile (compressed), description' hidden red spec zlib)" \
  "cprt=Copyright Astrid Holmvik $(canary ICCTEXT-PNG-CPRT "$F" 'iCCP profile (compressed), copyright' hidden red spec zlib)"
cat > "$W/ip.json" <<EOF
{
  "base": "$W/ip-base.png",
  "out": "$OUT/$F",
  "before": [
    {"type": "iCCP", "name": "Astrid $(canary ICCTEXT-PNG-NAME "$F" 'iCCP profile name field (a name, not a known profile name)' hidden red spec)", "file": "ip.icc"}
  ]
}
EOF
kit png-build "$W/ip.json"

F=webp-icc-text.webp
magick "$W/it.png" -strip -quality 80 -define webp:lossless=false -define webp:method=4 "$W/iw.webp"
kit icc-text "$ICC_SRC" "$W/iw.icc" ascii \
  "cprt=Copyright Astrid Holmvik $(canary ICCTEXT-WEBP-CPRT "$F" 'ICCP chunk, copyright' hidden red spec)" \
  "dmdd=Astrid Holmvik $(canary ICCTEXT-WEBP-DMDD "$F" 'ICCP chunk, device model description' hidden red spec)"
et "-ICC_Profile<=$W/iw.icc" "$W/iw.webp"
cp "$W/iw.webp" "$OUT/$F"

F=heic-icc-text.heic
kit icc-text "$ICC_SRC" "$W/ih.icc" mluc \
  "desc=Astrid Holmvik $(canary ICCTEXT-HEIC-DESC "$F" 'colr property (ICC profile), mluc description' hidden red spec utf16)" \
  "cprt=Copyright Astrid Holmvik $(canary ICCTEXT-HEIC-CPRT "$F" 'colr property (ICC profile), mluc copyright' hidden red spec utf16)"
magick "$W/it.png" -profile "$W/ih.icc" -depth 8 -quality 60 "$OUT/$F"

F=jpeg-green-xmp.jpg
jpg "$W/it.png" "$W/ix.jpg" 90
cat > "$W/ix.xml" <<EOF
<x:xmpmeta xmlns:x="adobe:ns:meta/">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
    xmlns:xmp="http://ns.adobe.com/xap/1.0/"
    xmlns:photoshop="http://ns.adobe.com/photoshop/1.0/"
    xmlns:GPano="http://ns.google.com/photos/1.0/panorama/"
    xmp:Rating="Astrid Holmvik $(canary GREENXMP-RATING "$F" 'XMP xmp:Rating holding text instead of a number' hidden red spec)"
    photoshop:ICCProfile="Astrid Holmvik $(canary GREENXMP-ICCPROFILE "$F" 'XMP photoshop:ICCProfile holding a name, not a known profile name' hidden red spec)"
    photoshop:ColorMode="3"
    GPano:ProjectionType="$(canary GREENXMP-GPANO-PROJECTION "$F" 'XMP GPano:ProjectionType holding text, not one of the projection names' hidden red spec)"
    GPano:PoseHeadingDegrees="12.5"/>
 </rdf:RDF>
</x:xmpmeta>
EOF
kit xmp-payload "$W/ix.xml" "$W/ix-xmp.bin"
kit jpeg-insert "$W/ix.jpg" "$OUT/$F" after:e0 "e1:$W/ix-xmp.bin"

# Checks and reports ##########################################################
rm -rf "$W"
kit verify "$REG" "$OUT"
LARGE=$(stat -c %s "$OUT/jpeg-large.jpg")
[ "$LARGE" -ge 6000000 ] || { echo "make-fixtures: jpeg-large.jpg is only $LARGE bytes" >&2; exit 1; }
[ "$(stat -c %s "$OUT/truncated.jpg")" -eq 2048 ] || { echo "make-fixtures: truncated.jpg is not 2,048 bytes" >&2; exit 1; }
kit visibility "$REG" "$OUT" "$OUT/exiftool" "$OUT/exiftool-visibility.tsv"
kit report "$REG" "$OUT/exiftool-visibility.tsv" "$OUT/canaries-tables.md"

# CANARIES.md must document every planted string.
MISSING=0
while IFS=$'\t' read -r s _; do
  [ "$s" = string ] && continue
  grep -qF -e "$s" "$HERE/CANARIES.md" 2>/dev/null || { echo "make-fixtures: not in CANARIES.md: $s" >&2; MISSING=1; }
done < "$REG"
[ "$MISSING" = 0 ] || echo "make-fixtures: CANARIES.md is stale; compare it with out/canaries-tables.md" >&2

(cd "$OUT" && find . -maxdepth 1 -type f ! -name '.*' ! -name SHA256SUMS -printf '%P\n' | sort | xargs sha256sum > SHA256SUMS)
echo "make-fixtures: done. Fixtures in $OUT"
(cd "$OUT" && find . -maxdepth 1 -type f \( -name '*.jpg' -o -name '*.png' -o -name '*.webp' -o -name '*.heic' -o -name '*.pdf' \) -printf '%10s  %P\n' | sort -k2)
